apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../components/revision-history-limit
  - ../components/strategy-recreate
  - ../components/oauth-ingress
  - ../components/gpu-workload

resources:
  - ai
  - iot
