apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../components/revision-history-limit
  - ../components/strategy-recreate
  - ../components/oauth-ingress
  - ../components/sqlite-backup

resources:
  - helm-releases.yaml
  - backup
  - backup/velero.yaml
  - ci
  - networking
  - observability
  - security
  - storage
