apiVersion: 1

# NOTE: deleteDatasources는 UI에서 수동 등록된 동명 데이터소스를 선언으로 넘겨받기 위한 것
deleteDatasources:
  - name: Loki
    orgId: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: false
