default_config:

homeassistant:
  external_url: "https://ha.${DOMAIN_EXTERNAL}"
  internal_url: "https://${SUB_HOMEASSISTANT}.${DOMAIN_LAN}"
  packages: !include_dir_named custom

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 127.0.0.1

wake_on_lan:
