apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: default
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: "${DEFAULT_USERNAME}"
  GF_SECURITY_ADMIN_PASSWORD: "${DEFAULT_PASSWORD}"
  GF_DATABASE_PASSWORD: "${DB_PASSWORD_GRAFANA}"
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "${POCKET_ID_OIDC_GRAFANA}"
