apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - gitea.yaml
  - act-runner-amd64.yaml
  - act-runner-arm64.yaml
  - secrets.yaml
configMapGenerator:
  - name: act-runner
    files:
      - act-runner/config.yaml
      - act-runner/entrypoint.sh
  - name: gitea
    literals:
      - TZ=${TZ}
      - GITEA__server__ROOT_URL=https://${SUB_GITEA}.${DOMAIN_LAN}/
      - GITEA__server__DOMAIN=${SUB_GITEA}.${DOMAIN_LAN}
      - GITEA__server__SSH_DOMAIN=${SUB_GITEA}.${DOMAIN_LAN}
      - GITEA__server__DISABLE_SSH=true
      - GITEA__packages__ENABLE_CONTAINER_ANONYMOUS_ACCESS=true
      - SSL_CERT_FILE=/etc/ssl/custom/ca.crt
      - GITEA__oauth2_client__ENABLE_AUTO_REGISTRATION=true
      - GITEA__oauth2_client__ACCOUNT_LINKING=auto
      - GITEA__oauth2_client__USERNAME=email
secretGenerator:
  - name: gitea-registry
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=gitea/registry-auth.json
