apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard.yaml
  - cloudflared.yaml
  - secrets.yaml
configMapGenerator:
  - name: coredns-custom
    namespace: kube-system
    options:
      disableNameSuffixHash: true
    files:
      - coredns/lan.server
  - name: adguard
    namespace: default
    options:
      disableNameSuffixHash: true
    files:
      - adguard/adguard-home.yaml
